export const MESSAGE_TYPES = {
  // Content script messages
  GET_VIDEO_INFO: 'GET_VIDEO_INFO',
  EXTRACT_TRANSCRIPT: 'EXTRACT_TRANSCRIPT',
  GET_CURRENT_TIME: 'GET_CURRENT_TIME',
  
  // Background script messages
  SAVE_NOTE: 'SAVE_NOTE',
  GET_NOTES: 'GET_NOTES',
  DELETE_NOTE: 'DELETE_NOTE',
  SAVE_TRANSCRIPT: 'SAVE_TRANSCRIPT',
  GET_TRANSCRIPTS: 'GET_TRANSCRIPTS',
  
  // API messages
  API_REQUEST: 'API_REQUEST',
  
  // Settings messages
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  
  // Sync messages
  SYNC_DATA: 'SYNC_DATA',
  SYNC_COMPLETE: 'SYNC_COMPLETE'
};
